package uk.co.instanto.integration;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.teavm.jso.JSBody;
import org.teavm.jso.JSObject;
import org.teavm.junit.TeaVMTestRunner;
import uk.co.instanto.client.service.RpcClient;
import uk.co.instanto.client.service.UnitRegistry;
import dev.verrai.rpc.teavm.WebWorkerTransport;
import uk.co.instanto.integration.service.MyDataService;
import uk.co.instanto.integration.service.dto.MyData;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.teavm.junit.SkipJVM;

@RunWith(TeaVMTestRunner.class)
public class TeaVMWebWorkerTest {

    @Test
    @SkipJVM
    public void testWorkerRpcSerialization() {
        // 1. Create a fake worker
        FakeWorker worker = createFakeWorker();

        // 2. Create Transport and Client (Composition)
        WebWorkerTransport transport = new WebWorkerTransport(worker);
        UnitRegistry.getInstance().registerRemote(uk.co.instanto.integration.service.MyDataService.class.getName(), "teavm-worker", transport);

        // 3. Create a static stub for MyDataService (Generated by processor)
        uk.co.instanto.integration.service.MyDataService stub = new uk.co.instanto.integration.service.MyDataService_Stub();

        // 4. Call a method
        MyData data = new MyData();
        data.setContent("Hello TeaVM");
        stub.processData(data); // This is a void method, so it sends a one-way message or we assume async
                                // without return for now in this simple test

        // 5. Verify the worker received a message
        JSObject lastMessage = worker.getLastMessage();
        assertNotNull("Worker should have received a message", lastMessage);

        System.out.println("TeaVM Test: Worker received RPC message successfully");
    }

    @Test
    public void testCodecEncodingDecoding() {
        // Verify that we can encode/decode using generated codecs in TeaVM environment
        MyData original = new MyData();
        original.setId("test-id");
        original.setContent("Codec Test Content");
        original.setValue(123);

        uk.co.instanto.integration.service.dto.MyDataCodec codec = new uk.co.instanto.integration.service.dto.MyDataCodec();

        // 1. POJO -> Wire
        uk.co.instanto.integration.service.dto.proto.MyData wireMsg = codec.toWire(original);
        assertNotNull(wireMsg);

        // 2. Wire -> Bytes (using Adapter)
        byte[] encoded = codec.getWireAdapter().encode(wireMsg);
        assertNotNull(encoded);

        try {
            // 3. Bytes -> Wire
            uk.co.instanto.integration.service.dto.proto.MyData decodedWire = codec.getWireAdapter().decode(encoded);

            // 4. Wire -> POJO
            MyData decoded = codec.fromWire(decodedWire);

            assertEquals(original.getId(), decoded.getId());
            assertEquals(original.getContent(), decoded.getContent());
            assertEquals(original.getValue(), decoded.getValue());
            System.out.println("TeaVM Test: Codec encode/decode successful");
        } catch (java.io.IOException e) {
            throw new RuntimeException(e);
        }
    }

    @JSBody(script = "return { lastMessage: null, postMessage: function(msg) { this.lastMessage = msg; }, getLastMessage: function() { return this.lastMessage; } };")
    private static native FakeWorker createFakeWorker();

    interface FakeWorker extends JSObject {
        JSObject getLastMessage();
    }
}
