package dev.verrai.processor;

import com.google.testing.compile.Compilation;
import org.junit.Test;

import static com.google.testing.compile.CompilationSubject.assertThat;
import static org.junit.Assert.*;

/**
 * Tests for ErrorBus dispatch code generated by {@link NavigationProcessor} /
 * {@link dev.verrai.processor.visitor.NavigationImplWriter}.
 */
public class ErrorHandlingProcessorTest {

    @Test
    public void start_registersDefaultErrorHandler() {
        Compilation c = ProcessorTestHelper.compileWithNavigation(
                ProcessorTestHelper.startingPage("home"));
        assertThat(c).succeeded();
        String nav = ProcessorTestHelper.generatedSource(c, "dev.verrai.impl.NavigationImpl");
        assertTrue("start() should register default ErrorBus handler",
                nav.contains("ErrorBus.register"));
        assertTrue("Default handler should check hasHandlers()",
                nav.contains("ErrorBus.hasHandlers"));
    }

    @Test
    public void start_wrapsNavigationInTryCatch() {
        Compilation c = ProcessorTestHelper.compileWithNavigation(
                ProcessorTestHelper.startingPage("home"),
                ProcessorTestHelper.page("about"));
        assertThat(c).succeeded();
        String nav = ProcessorTestHelper.generatedSource(c, "dev.verrai.impl.NavigationImpl");
        assertTrue("start() should dispatch on catch",
                nav.contains("ErrorBus.dispatch(\"navigation.start\""));
    }

    @Test
    public void goTo_wrapsPageLifecycleInTryCatch() {
        Compilation c = ProcessorTestHelper.compileWithNavigation(
                ProcessorTestHelper.startingPage("home"),
                ProcessorTestHelper.page("about"));
        assertThat(c).succeeded();
        String nav = ProcessorTestHelper.generatedSource(c, "dev.verrai.impl.NavigationImpl");
        assertTrue("goTo case should dispatch navigation error",
                nav.contains("ErrorBus.dispatch(\"navigation.goTo."));
    }

    @Test
    public void clearBindings_wrappedInSeparateTryCatch() {
        Compilation c = ProcessorTestHelper.compileWithNavigation(
                ProcessorTestHelper.startingPage("home"));
        assertThat(c).succeeded();
        String nav = ProcessorTestHelper.generatedSource(c, "dev.verrai.impl.NavigationImpl");
        assertTrue("clearBindings should dispatch its own error",
                nav.contains("ErrorBus.dispatch(\"navigation.clearBindings\""));
    }
}
