package dev.verrai.sample;

import uk.co.instanto.client.service.WorkerBootstrap;
import uk.co.instanto.client.service.UnitRegistry;
import dev.verrai.rpc.teavm.WebWorkerTransport;
import org.teavm.jso.JSBody;
import org.teavm.jso.JSObject;

public class WorkerEntry {

    public static void main(String[] args) {
        JSObject self = self();
        WebWorkerTransport transport = new WebWorkerTransport(self);
        WorkerBootstrap bootstrap = new WorkerBootstrap(transport);

        // Register Dispatcher (Generated by verrai-annotation-processor)
        bootstrap.registerDispatcher(AuthenticationService.class.getName(), new AuthenticationService_Dispatcher());

        // Register Implementation
        UnitRegistry.register(AuthenticationService.class, new AuthenticationServiceImpl());

        System.out.println("Worker started and listening...");
    }

    @JSBody(script = "return self;")
    private static native JSObject self();
}
